services:
  db:
    image: postgres:alpine
    container_name: bookshop_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: bookshop
    ports: ["5432:5432"]
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d bookshop"]
      interval: 5s
      timeout: 3s
      retries: 20
    restart: unless-stopped

  app:
    build: .
    container_name: bookshop_app
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/app
    environment:
      DATABASE_HOST: db
    ports:
      - "8000:8000"
    command: >
      sh -c "
        python manage.py migrate --noinput &&
        python manage.py import_data &&
        python manage.py runserver 0.0.0.0:8000
      "
    restart: unless-stopped