# Generated by Django 5.1.4 on 2025-03-08 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0004_favorites_favoritesitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Favorites',
            new_name='Wishlist',
        ),
        migrations.CreateModel(
            name='WishlistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.book')),
                ('wishlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bookshop.wishlist')),
            ],
        ),
        migrations.DeleteModel(
            name='FavoritesItem',
        ),
    ]
