# Generated by Django 5.1.4 on 2025-04-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0008_alter_author_options_alter_book_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Отправлен', 'Отправлен'), ('Готов к получению', 'Готов к получению'), ('Отменён', 'Отменён')], default='В обработке', max_length=17, verbose_name='Статус заказа'),
        ),
    ]
