# Generated by Django 5.1.4 on 2025-04-29 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0009_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('В обработке', 'В обработке'), ('Отправлен', 'Отправлен'), ('Готов к получению', 'Готов к получению'), ('Получен', 'Получен'), ('Отменён', 'Отменён')], default='В обработке', max_length=17, verbose_name='Статус заказа'),
        ),
    ]
