# Generated by Django 5.1.4 on 2025-05-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0010_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='year',
            field=models.IntegerField(blank=True, null=True, verbose_name='Год публикации'),
        ),
    ]
