# Generated by Django 5.1.4 on 2025-07-19 06:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshop', '0011_alter_book_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=3, unique=True, verbose_name='Возрастной рейтинг')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='age_limit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='bookshop.agelimit', verbose_name='Возрастной рейтинг'),
        ),
    ]
